name = "prayer-app"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true
keep_vars = true

[vars]
AIRTABLE_BASE_ID = "app1TcNtvts4fkqdm"
LEADERS_TABLE_NAME = "Leaders"
PRAYER_REQUESTS_TABLE = "Personal Prayer Requests"
PRAYER_LOGS_TABLE = "Prayer Logs"
# New tables for Church Prayer Requests
NETWORKS_TABLE_NAME = "Networks"
ORGANIZATIONS_TABLE_NAME = "Organizations"
IN_PRAYER_REQUESTS_TABLE_NAME = "IN: Prayer Requests"
