name = "prayer-app"
main = "src/index.js"
compatibility_date = "2025-08-01"
workers_dev = true

[vars]
AIRTABLE_BASE_ID = "app1TcNtvts4fkqdm"
LEADERS_TABLE_NAME = "Leaders"
PRAYER_REQUESTS_TABLE = "Prayer Requests"
PRAYER_LOGS_TABLE = "Prayer Logs"
